feat: create external module `middleware-attach`
tymsai/tymsai-api pull request #299
Opened 2018-11-14 17:05 UTC by eldeni

- Module alias `@externalModules/` is created.
- Dependency `route-mapping` is renamed `@nodekit/route-mapper`.

Fixes https://github.com/marmoym/marmoym/issues/125

2018-11-14 17:06 UTC, eldeni commented
`wip`

2018-11-25 12:15 UTC, UnoRich approved these changes
well done~

2018-11-25 12:17 UTC, gazzua requested changes

2018-11-25 12:17 UTC, gazzua commented on src/config/marmoymConfig.ts
> +
remove

2018-11-25 12:29 UTC, gazzua approved these changes

2018-11-25 12:29 UTC, merged